mod common;

use common::db::{Engine, combined, engine, feature_command, run_feature, setup, test_dsn};
use sqlx::AnyPool;
use std::{
    io::{BufRead, BufReader, Read},
    process::{Output, Stdio},
    time::Duration,
};
use tokio::sync::oneshot;

// The fixture schema is shared, so DB tests run in a single thread (--test-threads=1).

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn insert_identity_and_uuid_pk() {
    let _g = setup().await;
    // companies: identity PK is omitted; users: uuid PK is generated by the client,
    // created_at NOT NULL with no default is filled with now(). Both rows are read
    // back by the generated PK — meaning last_insert_id_* were set.
    let src = "\
Feature: insert
  Scenario: identity and uuid
    Given I have \"companies\" with \"slug: acme\"
    Then I should have \"companies\" with \"id: <<last_insert_id_companies>>\"
    Given I have \"users\" with \"email: a@b.net\"
    Then I should have \"users\" with \"id: <<last_insert_id_users>>\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
    assert!(combined(&out).contains("failed: 0"), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn missing_not_null_without_default_fails_naming_column() {
    let _g = setup().await;
    // companies.slug NOT NULL with no default and no value → an error naming the column.
    let src = "\
Feature: insert
  Scenario: missing slug
    Given I have \"companies\" with \"name: no-slug\"
";
    let out = run_feature(src, &_g);
    assert!(!out.status.success(), "must fail: {}", combined(&out));
    assert!(combined(&out).contains("slug"), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn wide_table_insert_sets_indexed_vars() {
    let _g = setup().await;
    let src = "\
Feature: insert
  Scenario: table form
    Given I have \"companies\" where:
      | slug   |
      | first  |
      | second |
    Then I should have \"companies\" with \"id: <<last_insert_id_companies_0>>\"
    And I should have \"companies\" with \"id: <<last_insert_id_companies_1>>\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn update_sets_updated_counter() {
    let _g = setup().await;
    // updated_companies == 1 after UPDATE; the last step looks for an already
    // deleted row and must fail (I should not have arrives in Task 10).
    let src = "\
Feature: mutate
  Scenario: update counter
    Given I have \"companies\" with \"slug: acme\"
    When I update \"companies\" with \"name: Renamed\" where \"id: <<last_insert_id_companies>>\"
    Then variable \"updated_companies\" should be equal to \"1\"
    When I delete \"companies\" where \"id: <<last_insert_id_companies>>\"
    Then I should have \"companies\" with \"slug: acme\"
";
    let out = run_feature(src, &_g);
    assert!(
        !out.status.success(),
        "a deleted row must not be found: {}",
        combined(&out)
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn delete_all_empties_table() {
    let _g = setup().await;
    let src = "\
Feature: mutate
  Scenario: wipe table
    Given I have \"companies\" with \"slug: one\"
    And I have \"companies\" with \"slug: two\"
    When I delete all \"companies\"
    Then I should have \"companies\" with \"slug: one\"
";
    // after DELETE ALL the table is empty — the row lookup must fail.
    let out = run_feature(src, &_g);
    assert!(
        !out.status.success(),
        "the table must be empty: {}",
        combined(&out)
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn should_not_have_passes_for_absent_row() {
    let _g = setup().await;
    // The row with slug: acme exists; negating presence of a nonexistent slug passes.
    let src = "\
Feature: absence
  Scenario: negative existence ok
    Given I have \"companies\" with \"slug: acme\"
    Then I should not have \"companies\" with \"slug: ghost\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn should_not_have_fails_for_present_row() {
    let _g = setup().await;
    // Negating presence of an existing row must fail.
    let src = "\
Feature: absence
  Scenario: negative existence violated
    Given I have \"companies\" with \"slug: acme\"
    Then I should not have \"companies\" with \"slug: acme\"
";
    let out = run_feature(src, &_g);
    assert!(
        !out.status.success(),
        "an existing row must violate the negation: {}",
        combined(&out)
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn null_sentinel_insert_matches_is_null() {
    let _g = setup().await;
    // deleted_at is inserted as <<null>> (SQL NULL); a lookup by <<null>> goes through IS NULL.
    let src = "\
Feature: null
  Scenario: insert null and match is null
    Given I have \"users\" with \"email: a@b.net, deleted_at: <<null>>\"
    Then I should have \"users\" with \"deleted_at: <<null>>\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn composite_pk_insert_reads_back_via_last_insert_vars() {
    let _g = setup().await;
    // pair(a, b) is a composite PK; RETURNING stores last_insert_pair_a / _b,
    // which the row is then read back by.
    let src = "\
Feature: composite pk
  Scenario: insert and read back pair
    Given I have \"pair\" with \"a: 1, b: 2, note: linked\"
    Then I should have \"pair\" with \"a: <<last_insert_pair_a>>\"
    And I should have \"pair\" with \"b: <<last_insert_pair_b>>\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn delete_all_sets_deleted_counter() {
    let _g = setup().await;
    // deleted_companies == 2 after DELETE ALL over two rows.
    let src = "\
Feature: mutate
  Scenario: delete all counter
    Given I have \"companies\" with \"slug: one\"
    And I have \"companies\" with \"slug: two\"
    When I delete all \"companies\"
    Then variable \"deleted_companies\" should be equal to \"2\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn extract_from_table_binds_variable() {
    let _g = setup().await;
    // extract stores the column value in a variable; the next step checks it
    // via <<cid>> — a match confirms extract bound the variable.
    let src = "\
Feature: extract
  Scenario: pull id into var
    Given I have \"companies\" with \"slug: acme\"
    When I extract \"id\" from \"companies\" with \"slug: acme\" as \"cid\"
    Then I should have \"companies\" with \"id: <<cid>>\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn sequence_and_builtin_function() {
    let _g = setup().await;
    // nextval increases — on the engines that have sequences at all. MySQL has
    // none, and the message it refuses with is a user-facing contract.
    let src = "\
Feature: routines
  Scenario: sequence
    Given I get next value of sequence \"apibdd_it.thing_seq\" as \"first\"
    And I get next value of sequence \"apibdd_it.thing_seq\" as \"second\"
    Then variable \"second\" should not be equal to \"<<first>>\"
";
    let out = run_feature(src, &_g);
    if engine() == Engine::MySql {
        assert!(!out.status.success(), "{}", combined(&out));
        assert!(
            combined(&out).contains("sequences are not supported on mysql"),
            "{}",
            combined(&out)
        );
    } else {
        assert!(out.status.success(), "{}", combined(&out));
    }

    // upper() is a builtin function taking a text argument — on every engine.
    let src = "\
Feature: routines
  Scenario: function
    When I call function \"upper\" with \"s: abc\" as \"up\"
    Then variable \"up\" should be equal to \"ABC\"
";
    let out = run_feature(src, &_g);
    assert!(out.status.success(), "{}", combined(&out));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn eventual_database_assertion_observes_delayed_row() {
    let _g = setup().await;
    let without_polling = run_feature(
        "\
Feature: eventual database assertion
  Scenario: row appears asynchronously
    Then I should have \"companies\" with \"slug: delayed-company\"
",
        &_g,
    );
    assert!(
        !without_polling.status.success(),
        "assertion unexpectedly passed without polling: {}",
        combined(&without_polling)
    );

    // The debug line the assertion prints is dialect-specific: Postgres casts
    // its binds, MySQL/MariaDB use a bare `?`. It is the oneshot trigger below,
    // so a hardcoded one would not fail the test — it would hang to timeout.
    let probe = format!(
        "SQL: SELECT 1 FROM companies WHERE slug = {} LIMIT 1",
        match engine() {
            Engine::Postgres => "$1::text",
            Engine::MySql | Engine::MariaDb => "?",
        }
    );
    let delayed = AnyPool::connect(&test_dsn())
        .await
        .expect("connect delayed inserter");
    let (first_query, first_query_seen) = oneshot::channel();
    let inserter = tokio::spawn(async move {
        first_query_seen
            .await
            .expect("first assertion query signal dropped");
        tokio::time::sleep(Duration::from_millis(200)).await;
        sqlx::query("INSERT INTO apibdd_it.companies (slug) VALUES ('delayed-company')")
            .execute(&delayed)
            .await
            .expect("insert delayed company");
        delayed.close().await;
    });
    let mut child = feature_command(
        "\
Feature: eventual database assertion
  Scenario: row appears asynchronously
    Given I am in debug mode
    And I expect the next assertion to pass within \"2\" seconds, checking every \"50\" milliseconds
    Then I should have \"companies\" with \"slug: delayed-company\"
",
    )
    .stdout(Stdio::piped())
    .stderr(Stdio::piped())
    .spawn()
    .expect("start bddkit");
    let stdout = child.stdout.take().expect("capture bddkit stdout");
    let stderr = child.stderr.take().expect("capture bddkit stderr");
    let stdout_reader = std::thread::spawn(move || {
        let mut stdout_bytes = Vec::new();
        BufReader::new(stdout)
            .read_to_end(&mut stdout_bytes)
            .expect("read bddkit stdout");
        stdout_bytes
    });
    let probe_line = probe.clone();
    let reader = std::thread::spawn(move || {
        let mut stderr_bytes = Vec::new();
        let mut first_query = Some(first_query);
        for line in BufReader::new(stderr).split(b'\n') {
            let line = line.expect("read bddkit stderr");
            if line == probe_line.as_bytes()
                && let Some(first_query) = first_query.take()
            {
                first_query
                    .send(())
                    .expect("delayed inserter stopped early");
            }
            stderr_bytes.extend_from_slice(&line);
            stderr_bytes.push(b'\n');
        }
        stderr_bytes
    });
    let status = child.wait().expect("wait for bddkit");
    let with_polling = Output {
        status,
        stdout: stdout_reader.join().expect("stdout reader panicked"),
        stderr: reader.join().expect("stderr reader panicked"),
    };
    inserter.await.expect("delayed inserter panicked");
    let output = combined(&with_polling);
    assert!(with_polling.status.success(), "{output}");
    assert!(
        output.matches(probe.as_str()).count() >= 2,
        "polling assertion did not make an initial miss and retry: {output}"
    );
}
